### ISSUE TITLE
Doesn't work on Python 3

### ISSUE THREAD

**Issue by Garrett-R** [eillarra/wkhtmltopdf-pack#1]
When I try to do `pip install wkhtmltopdf-pack` , I get:

```python
Collecting wkhtmltopdf-pack
  Using cached wkhtmltopdf-pack-0.12.3.0.tar.gz
Installing collected packages: wkhtmltopdf-pack
  Running setup.py install for wkhtmltopdf-pack
    Complete output from command /home/garrett/Dropbox/upcodes/upcodes/.venv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-gkd41bcx/wkhtmltopdf-pack/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-r4idequn-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/garrett/Dropbox/upcodes/upcodes/.venv/include/site/python3.5/wkhtmltopdf-pack:
    running install
    running build
    running build_scripts
    creating build
    creating build/scripts-3.5
    Traceback (most recent call last):
      File "/home/garrett/Dropbox/upcodes/upcodes/.venv/lib/python3.5/tokenize.py", line 392, in find_cookie
        line_string = line.decode('utf-8')
    UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 24-25: invalid continuation byte
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gkd41bcx/wkhtmltopdf-pack/setup.py", line 24, in <module>
        zip_safe=False
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/garrett/Dropbox/upcodes/upcodes/.venv/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build_scripts.py", line 50, in run
        self.copy_scripts()
      File "/usr/lib/python3.5/distutils/command/build_scripts.py", line 82, in copy_scripts
        encoding, lines = tokenize.detect_encoding(f.readline)
      File "/home/garrett/Dropbox/upcodes/upcodes/.venv/lib/python3.5/tokenize.py", line 433, in detect_encoding
        encoding = find_cookie(first)
      File "/home/garrett/Dropbox/upcodes/upcodes/.venv/lib/python3.5/tokenize.py", line 397, in find_cookie
        raise SyntaxError(msg)
    

```

**Comment by pwaldo2** [comment]
I can't seem to install this in Python 3 either:

```
$ pip install wkhtmltopdf-pack
Collecting wkhtmltopdf-pack
  Downloading wkhtmltopdf-pack-0.12.3.0.tar.gz (15.2MB)
    100% |████████████████████████████████| 15.2MB 112kB/s 
Building wheels for collected packages: wkhtmltopdf-pack
  Running setup.py bdist_wheel for wkhtmltopdf-pack ... error
  Complete output from command /Users/me/temp/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/2_/vsq87n793k96q5j33ny610680000gn/T/pip-build-jvdqw47k/wkhtmltopdf-pack/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/2_/vsq87n793k96q5j33ny610680000gn/T/tmpfekggj51pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_scripts
  creating build
  creating build/scripts-3.6
  Traceback (most recent call last):
    File "/Users/me/temp/venv/lib/python3.6/tokenize.py", line 390, in find_cookie
      line_string = line.decode('utf-8')
  UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 24-25: invalid continuation byte
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/2_/vsq87n793k96q5j33ny610680000gn/T/pip-build-jvdqw47k/wkhtmltopdf-pack/setup.py", line 24, in <module>
      zip_safe=False
    File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/me/temp/venv/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 50, in run
      self.copy_scripts()
    File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 82, in copy_scripts
      encoding, lines = tokenize.detect_encoding(f.readline)
    File "/Users/me/temp/venv/lib/python3.6/tokenize.py", line 431, in detect_encoding
      encoding = find_cookie(first)
    File "/Users/me/temp/venv/lib/python3.6/tokenize.py", line 395, in find_cookie
      raise SyntaxError(msg)
  SyntaxError: invalid or missing encoding declaration for 'bin/wkhtmltopdf-pack'
  
  ----------------------------------------
  Failed building wheel for wkhtmltopdf-pack
  Running setup.py clean for wkhtmltopdf-pack
Failed to build wkhtmltopdf-pack
Installing collected packages: wkhtmltopdf-pack
  Running setup.py install for wkhtmltopdf-pack ... error
    Complete output from command /Users/me/temp/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/2_/vsq87n793k96q5j33ny610680000gn/T/pip-build-jvdqw47k/wkhtmltopdf-pack/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/2_/vsq87n793k96q5j33ny610680000gn/T/pip-zd8t_tdj-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/me/temp/venv/bin/../include/site/python3.6/wkhtmltopdf-pack:
    running install
    running build
    running build_scripts
    creating build
    creating build/scripts-3.6
    Traceback (most recent call last):
      File "/Users/me/temp/venv/lib/python3.6/tokenize.py", line 390, in find_cookie
        line_string = line.decode('utf-8')
    UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 24-25: invalid continuation byte
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2_/vsq87n793k96q5j33ny610680000gn/T/pip-build-jvdqw47k/wkhtmltopdf-pack/setup.py", line 24, in <module>
        zip_safe=False
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/me/temp/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 50, in run
        self.copy_scripts()
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_scripts.py", line 82, in copy_scripts
        encoding, lines = tokenize.detect_encoding(f.readline)
      File "/Users/me/temp/venv/lib/python3.6/tokenize.py", line 431, in detect_encoding
        encoding = find_cookie(first)
      File "/Users/me/temp/venv/lib/python3.6/tokenize.py", line 395, in find_cookie
        raise SyntaxError(msg)
    SyntaxError: invalid or missing encoding declaration for 'bin/wkhtmltopdf-pack'
    
    ----------------------------------------
Command "/Users/me/temp/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/2_/vsq87n793k96q5j33ny610680000gn/T/pip-build-jvdqw47k/wkhtmltopdf-pack/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/2_/vsq87n793k96q5j33ny610680000gn/T/pip-zd8t_tdj-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/me/temp/venv/bin/../include/site/python3.6/wkhtmltopdf-pack" failed with error code 1 in /private/var/folders/2_/vsq87n793k96q5j33ny610680000gn/T/pip-build-jvdqw47k/wkhtmltopdf-pack/

```
